server:
  port: 8083

spring:
  application:
    name: customer

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # default address
